"""
data.py
-------
Loads the three cleaned CE paradata files (MCHI, FPAR, FMLI) once at process
start and builds the household-level joins the dashboard tabs need.

Input:  data/processed/mchi_clean.csv, fpar_clean.csv, fmli_clean.csv
        (generated by scripts/clean_mchi.py, clean_fpar.py, clean_fmli.py)
"""

import os
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROCESSED_DIR = os.path.join(ROOT, "data", "processed")

MCHI_NUMERIC = ["contact_attempts", "days_in_field", "completed", "htc_segment_count",
                "htc_hard_to_interview", "htc_hard_to_persuade",
                "htc_hard_to_locate", "htc_hard_to_contact", "max_wave"]


def load_data():
    mchi = pd.read_csv(os.path.join(PROCESSED_DIR, "mchi_clean.csv"), low_memory=False)
    for col in MCHI_NUMERIC:
        mchi[col] = pd.to_numeric(mchi[col], errors="coerce")

    fpar = pd.read_csv(os.path.join(PROCESSED_DIR, "fpar_clean.csv"), low_memory=False)
    # OUTCOME is written as a string code ("201") by clean_fpar.py, but with
    # no dtype hint on reload here pandas infers it as int64 -- silently
    # breaking any `== "201"` string comparison below (0 rows match, no error).
    fpar["OUTCOME"] = fpar["OUTCOME"].astype(str)
    fmli = pd.read_csv(os.path.join(PROCESSED_DIR, "fmli_clean.csv"), low_memory=False)

    htc_cols = ["CUID", "completed", "htc_segment_count", "htc_hard_to_interview",
                "htc_hard_to_persuade", "htc_hard_to_locate", "htc_hard_to_contact",
                "contact_attempts", "max_wave"]

    # --- FPAR aggregated to one row per household ---
    # ever_converted: any wave where CONVREF flagged a converted refusal.
    ever_converted = (
        fpar.groupby("CUID")["CONVREF"]
        .apply(lambda s: (s == 1).any())
        .rename("ever_converted")
        .reset_index()
    )
    # Mode of the wave that actually completed (HOW_INTV), not the attempted-mode
    # field TELPV -- see findings_report.md Finding 8 for why TELPV was retracted.
    # A household can have more than one completed wave over the panel (FPAR is
    # one row per household PER WAVE); this dashboard joins at the household
    # level to match MCHI's other columns, so we keep each household's most
    # recent completed wave -- same "last/most-recent" convention already used
    # for final_outcome in clean_mchi.py and for wave selection in clean_fmli.py.
    # (Finding 8's report numbers are computed at the wave level instead, so
    # they won't match this household-level count one-for-one -- different
    # grain, not a discrepancy.)
    completed_wave = (
        fpar[fpar["OUTCOME"] == "201"][["CUID", "QYEAR", "how_intv_label"]]
        .sort_values(["CUID", "QYEAR"])
        .drop_duplicates("CUID", keep="last")
    )

    def mode_group(label):
        if not isinstance(label, str):
            return "Unknown"
        if label == "Evenly split personal visit / phone":
            return "Evenly split"
        if "Personal visit" in label:
            return "Personal visit"
        if "Phone" in label:
            return "Phone"
        return "Unknown"

    completed_wave = completed_wave.copy()
    completed_wave["mode_group"] = completed_wave["how_intv_label"].map(mode_group)

    fpar_household = (
        mchi[htc_cols]
        .merge(ever_converted, on="CUID", how="left")
        .merge(completed_wave[["CUID", "mode_group"]], on="CUID", how="left")
    )
    fpar_household["ever_converted"] = fpar_household["ever_converted"].fillna(False)

    # --- FMLI joined to MCHI's HTC/completion columns ---
    fmli_household = fmli.merge(mchi[htc_cols], on="CUID", how="left")
    fmli_household["at_least_one_htc"] = (fmli_household["htc_segment_count"] >= 1).astype(int)
    fmli_household["age_band"] = pd.cut(
        fmli_household["AGE_REF"], bins=[0, 34, 49, 64, 150],
        labels=["≤34", "35–49", "50–64", "65+"],
    )

    return {
        "mchi": mchi,
        "fpar": fpar,
        "fmli": fmli,
        "fpar_household": fpar_household,
        "fmli_household": fmli_household,
    }
